### ISSUE TITLE
Connecting to 10.5.0.2:8080... failed: Connection timed out

### ISSUE THREAD

**Issue by shiyuw3** [CamFlow/examples#1]
When I compile the examples successfully and tried to implement the UCSC case, it showed that Connecting to 10.5.0.2:8080... failed: Connection timed out. Could anyone give some advice? Thanks ahead.

**Comment by tfjmp** [comment]
Hum... sadly I am not very familiar with UCSC example. It has been a while, and it should probably have been removed from the repository. What are you trying to do? I may be able to help you setup an example.

**Comment by shiyuw3** [comment]
well, I have loaded the kernel successfully and the camflow could record the behavior like wget. So I am wondering if there are more cases to varify its functionality.

**Comment by tfjmp** [comment]
Have you a particular project in mind? I am happy to help you get started. If you let me know your e-mail address we can discuss further on slack.

**Comment by shiyuw3** [comment]
Not yet, just want to play with some toy cases. Thanks for your help!
